Url_rewrite_nav/learning_templates/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

##Template Tagging
app_name = 'basicapp'
urlpatterns = [
    url('relative/',views.relative,name='relative'),
    url('others/',views.others,name='others'), 
]

Url_rewrite_nav/learning_templates/learning_templates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path
from basicapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('basicapp/',include('basicapp.urls',namespace='basicapp')),
    path('admin/', admin.site.urls),
]

Url_rewrite_nav/learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

Url_rewrite_nav/learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text': 'hello world','number':100}
    return render(request,'basicapp/index.html',context_dict)

def others(request):
    return render(request,'basicapp/others.html')

def relative(request):
    return render(request,'basicapp/relative_url_template.html')

Url_rewrite_nav/learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- CSS only -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li><a class="navbar-brand" href="{% url 'index'%}">BRAND</a></li>
      <li><a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a></li>
      <li><a class="nav-link" href="{% url 'basicapp:others' %}">OTHERS</a></li>
    </ul>
  </div>
</nav>
<div class="container">
  {% block body_block %}
  {% endblock %}
</div>
  </body>
</html>

Url_rewrite_nav/learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html"%}
{% block body_block%}
<h1>Welcom to index!</h1>
  <h2>This is the index.html page showing!</h2>
  <h1>{{ text|cut:'world' }} : {{ number|add:"99" }}</h1>

  {% endblock %}

Url_rewrite_nav/learning_templates/templates/basicapp/others.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
<h1>Welcom to Others!</h1>
<h2>This is an example of template inheritance!</h2>
{% endblock %}

Url_rewrite_nav/learning_templates/templates/basicapp/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<h1>Welcom to Relative Url templates</h1>
<a href="{% url 'basicapp:others' %}"> The other page</a>
<a href="{% url 'admin:index' %}"> Link to Admin</a>
<a href="{% url 'index' %}"> Link to Index</a>
  </body>
</html>